#log:
  #level: DEBUG
#  level: INFO
#  filePath: "/var/log/traefik/traefik.log"
accessLog:
  filePath: "/var/log/traefik/access.log"
  format: json
  bufferingSize: 10
  fields:
    defaultMode: keep
    headers:
      defaultMode: keep
      names:
        Cookie: drop
      #names:
      #  ServiceURL: keep
api:
  insecure: true
  dashboard: true
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http2:
      maxConcurrentStreams: 500
ping:
  entryPoint: "traefik"
providers:
  file:
    filename: /etc/traefik/traefik-dynamic.yml
metrics:
  prometheus:
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true
#experimental:
#  plugins:
#    cloudflarewarp:
#      modulename: github.com/BetterCorp/cloudflarewarp
#      version: v1.3.3