root = "."
testdata_dir = "testdata"
#tmp_dir = "tmp"
tmp_dir = "/tmp"

[build]
args_bin = []
#bin = "./tmp/main"
bin = "/usr/bin/app"
#cmd = """go build -buildvcs=false -ldflags "
#-X 'go.szostok.io/version.version=0.0.1'
#-X 'go.szostok.io/version.buildDate=`date`'
#" -o ./tmp/main ."""
cmd = """go build -buildvcs=false -ldflags "
-X 'go.szostok.io/version.version=0.0.1'
-X 'go.szostok.io/version.buildDate=`date`'
" -o /usr/bin/app ."""
# DELAY it's very necessary, because sometimes it can start the build process multiple times!
delay = 1000
exclude_dir = ["assets", "tmp", "vendor", "testdata", "bin", "docker", "build", "public", ".idea"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html"]
include_file = []
kill_delay = "0s"
log = "build-errors.log"
rerun = false
rerun_delay = 500
send_interrupt = false
stop_onerrLog = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
keep_scroll = true
